export const quotes = [
    "“Programs must be written for people to read, and only incidentally for machines to execute.” – Harold Abelson",
    "“Experience is the name everyone gives to their mistakes.” – Oscar Wilde",
    "“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler",
    "“First, solve the problem. Then, write the code.” – John Johnson",
    "“Code is like humor. When you have to explain it, it’s bad.” – Cory House",
    "“Simplicity is the soul of efficiency.” – Austin Freeman",
    "“The best error message is the one that never shows up.” – Thomas Fuchs",
    "“Programming isn’t about what you know; it’s about what you can figure out.” – Chris Pine",
    "“The only way to learn a new programming language is by writing programs in it.” – Dennis Ritchie",
    "“Make it work, make it right, make it fast.” – Kent Beck",
    "“Talk is cheap. Show me the code.” – Linus Torvalds",
    "“Programs are meant to be read by humans and only incidentally for computers to execute.” – Donald Knuth",
    "“If you optimize everything, you will always be unhappy.” – Donald Knuth",
    "“Any sufficiently advanced technology is indistinguishable from magic.” – Arthur C. Clarke",
    "“Walking on water and developing software from a specification are easy if both are frozen.” – Edward V Berard",
    "“Programming is the art of telling another human what one wants the computer to do.” – Donald Knuth",
    "“Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code.” – Dan Salomon",
    "“The most important property of a program is whether it accomplishes the intention of its user.” – C.A.R. Hoare",
    "“A good programmer is someone who looks both ways before crossing a one-way street.” – Doug Linder",
    "“The best way to get a project done faster is to start sooner.” – Jim Highsmith",
    "“Deleted code is debugged code.” – Jeff Sickel",
    "“Good code is its own best documentation.” – Steve McConnell",
    "“Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.” – John Woods",
    "“Measuring programming progress by lines of code is like measuring aircraft building progress by weight.” – Bill Gates",
    "“Programming without an overall architecture or design in mind is like exploring a cave with only a flashlight.” – Danny Thorpe",
    "“Any application that can be written in JavaScript, will eventually be written in JavaScript.” – Atwood’s Law",
    "“Learning to program is like learning a new language. The more you practice, the better you get.” – Unknown",
    "“Code never lies, comments sometimes do.” – Ron Jeffries",
    "“The function of good software is to make the complex appear simple.” – Grady Booch",
    "“The best programmers are not those who remember every syntax rule, but those who know how to solve problems.” – Unknown",
    "“Java is to JavaScript what car is to Carpet.” – Chris Heilmann",
    "“Don’t worry if it doesn’t work right. If everything did, you’d be out of a job.” – Mosher’s Law of Software Engineering",
    "“There are two ways to write error-free programs; only the third one works.” – Alan J. Perlis",
    "“It’s not a bug – it’s an undocumented feature.” – Unknown",
    "“Debugging is like being the detective in a crime movie where you are also the murderer.” – Filipe Fortes",
    "“Programming languages, like pizzas, come in all shapes and sizes. Some are cheesy, some are spicy, and some are just plain weird.” – Unknown",
    "“A language that doesn’t affect the way you think about programming is not worth knowing.” – Alan J. Perlis",
    "“You can’t have great software without a great team, and most software teams behave like dysfunctional families.” – Jim McCarthy",
    "“If debugging is the process of removing bugs, then programming must be the process of putting them in.” – Edsger Dijkstra",
    "“Computers are fast; programmers keep it slow.” – Unknown",
    "“The best way to learn to code is to write code.” – Unknown",
    "“Programming isn’t about typing, it’s about thinking.” – Rich Hickey",
    "“Code is read much more often than it is written.” – Guido van Rossum",
    "“Software is a great combination of artistry and engineering.” – Bill Gates",
    "“It works on my machine.” – Every Programmer Ever",
    "“Programming: Where the most random things fix the most annoying bugs.” – Unknown",
    "“You should name a variable using the same care with which you name a first-born child.” – Robert C. Martin",
  ];
  